// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolyclinicWeb.Classes;

#nullable disable

namespace PolyclinicWeb.Migrations
{
    [DbContext(typeof(PolyclinicContext))]
    [Migration("20221021180506_Type")]
    partial class Type
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PolyclinicWeb.Classes.AdditionalRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("DiaryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DiaryId");

                    b.ToTable("AdditionalRecommendations");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.ClinicalDiagnosis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("DiaryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Main")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DiaryId");

                    b.ToTable("ClinicalDiagnoses");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Diary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Complaints")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MedicalWorker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectiveData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Profession")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Diarys");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.DispensaryDiagnosis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("DeregistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("DispensaryDiagnoses");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.IndicatorOfLaboratoryTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Indicator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("LaboratoryTestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LaboratoryTestId");

                    b.ToTable("IndicatorsOfLaboratoryTests");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.InstrumentalTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("InstrumentalTests");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.LaboratoryTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("LaboratoryTests");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.MedicalRecommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("DiaryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DosesNumber")
                        .HasColumnType("int");

                    b.Property<string>("Drug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReleaseForm")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DiaryId");

                    b.ToTable("MedicationRecommendations");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AdditionalInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Locality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Plot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Plots");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Vaccination", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AdditionalInformation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint");

                    b.Property<string>("Production")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Vaccinations");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.AdditionalRecommendation", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Diary", "Diary")
                        .WithMany("AdditionalRecommendations")
                        .HasForeignKey("DiaryId");

                    b.Navigation("Diary");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.ClinicalDiagnosis", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Diary", "Diary")
                        .WithMany("ClinicalDiagnoses")
                        .HasForeignKey("DiaryId");

                    b.Navigation("Diary");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Diary", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Patient", "Patient")
                        .WithMany("Diarys")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.DispensaryDiagnosis", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Patient", "Patient")
                        .WithMany("DispensaryDiagnoses")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.IndicatorOfLaboratoryTest", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.LaboratoryTest", "LaboratoryTest")
                        .WithMany("IndicatorsOfLaboratoryTests")
                        .HasForeignKey("LaboratoryTestId");

                    b.Navigation("LaboratoryTest");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.InstrumentalTest", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Patient", "Patient")
                        .WithMany("InstrumentalTests")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.LaboratoryTest", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Patient", "Patient")
                        .WithMany("LaboratoryTests")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.MedicalRecommendation", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Diary", "Diary")
                        .WithMany("MedicationRecommendations")
                        .HasForeignKey("DiaryId");

                    b.Navigation("Diary");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Plot", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Patient", "Patient")
                        .WithMany("Plots")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Vaccination", b =>
                {
                    b.HasOne("PolyclinicWeb.Classes.Patient", "Patient")
                        .WithMany("Vaccinations")
                        .HasForeignKey("PatientId");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Diary", b =>
                {
                    b.Navigation("AdditionalRecommendations");

                    b.Navigation("ClinicalDiagnoses");

                    b.Navigation("MedicationRecommendations");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.LaboratoryTest", b =>
                {
                    b.Navigation("IndicatorsOfLaboratoryTests");
                });

            modelBuilder.Entity("PolyclinicWeb.Classes.Patient", b =>
                {
                    b.Navigation("Diarys");

                    b.Navigation("DispensaryDiagnoses");

                    b.Navigation("InstrumentalTests");

                    b.Navigation("LaboratoryTests");

                    b.Navigation("Plots");

                    b.Navigation("Vaccinations");
                });
#pragma warning restore 612, 618
        }
    }
}
